version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    restart: unless-stopped
  mongo-express:
    image: mongo-express:1
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports: ["8081:8081"]
    depends_on: [mongo]
